classification = {
    "martial arts term": "Martial Arts",
    "rude or X-rated term (not displayed in educational software)": "Rude",
    "abbreviation": "Abbr.",
    "adjective (keiyoushi)": "Adj.",
    "adjective (keiyoushi) - yoi/ii class": "",
    "adjectival nouns or quasi-adjectives (keiyodoshi)": "",
    "nouns which may take the genitive case particle `no'": "",
    "pre-noun adjectival (rentaishi)": "",
    "`taru' adjective": "",
    "noun or verb acting prenominally": "",
    "adverb (fukushi)": "Adverb",
    "adverb taking the `to' particle": "",
    "archaism": "Archaic",
    "ateji (phonetic) reading": "Ateji",
    "auxiliary": "Auxiliary",
    "auxiliary verb": "Aux. Verb",
    "auxiliary adjective": "Aux. Adj.",
    "Buddhist term": "Buddhism",
    "chemistry term": "Chemistry",
    "children's language": "Juvenile",
    "colloquialism": "Colloquial",
    "computer terminology": "Computer",
    "conjunction": "Conjunction",
    "copula": "Copula",
    "counter": "Counter",
    "derogatory": "Derog.",
    "exclusively kanji": "Only Kanji",
    "exclusively kana": "Only Kana",
    "expressions (phrases, clauses, etc.)": "Expression",
    "familiar language": "Familiar",
    "female term or language": "Feminine",
    "food term": "Food",
    "geometry term": "Geometry",
    "gikun (meaning as reading) or jukujikun (special kanji reading)": "Gikun/Jukujikun",
    "honorific or respectful (sonkeigo) language": "Honorific",
    "humble (kenjougo) language": "Humble",
    "word containing irregular kanji usage": "Irregular Kanji",
    "idiomatic expression": "Idiomatic",
    "word containing irregular kana usage": "Irregular Kana",
    "interjection (kandoushi)": "Interjection",
    "irregular okurigana usage": "Irregular Okurigana",
    "irregular verb": "Irregular Verb",
    "linguistics terminology": "Linguistic",
    "manga slang": "Manga",
    "male term or language": "Masculine",
    "male slang": "Male Slang",
    "mathematics": "Mathematical",
    "military": "Military",
    "noun (common) (futsuumeishi)": "Noun",
    "adverbial noun (fukushitekimeishi)": "Adv. Noun",
    "noun, used as a suffix": "Noun (Suffix)",
    "noun, used as a prefix": "Noun (Prefix)",
    "noun (temporal) (jisoumeishi)": "Noun (Temporal)",
    "numeric": "Numeric",
    "word containing out-dated kanji": "Outdated Kanji",
    "obsolete term": "Obsolete",
    "obscure term": "Obscure",
    "out-dated or obsolete kana usage": "",
    "old or irregular kana form": "",
    "onomatopoeic or mimetic word": "",
    "pronoun": "Pronoun",
    "poetical term": "",
    "polite (teineigo) language": "",
    "prefix": "Prefix",
    "proverb": "Proverb",
    "particle": "Particle",
    "physics terminology": "Physics",
    "quotation": "Quotation",
    "rare": "Rare",
    "sensitive": "Sensitive",
    "slang": "Slang",
    "suffix": "Suffix",
    "word usually written using kanji alone": "Usually Kanji",
    "word usually written using kana alone": "Usually Kana",
    "unclassified": "Unclassified",
    "yojijukugo": "",
    "Ichidan verb": "Ichidan",
    "Ichidan verb - kureru special class": "Ichidan (くれる)",
    "Nidan verb with 'u' ending (archaic)": "Nidan (-う) (Archaic)",
    "Yodan verb with `hu/fu' ending (archaic)": "Yodan (-ふ) (Archaic)",
    "Yodan verb with `ru' ending (archaic)": "Yodan (-る) (Archaic)",
    "Godan verb - -aru special class": "Godan (ある)",
    "Godan verb with `bu' ending": "Godan (ぶ)",
    "Godan verb with `gu' ending": "Godan (ぐ)",
    "Godan verb with `ku' ending": "Godan (く)",
    "Godan verb - Iku/Yuku special class": "Godan （いく/ゆく)",
    "Godan verb with `mu' ending": "Godan (む)",
    "Godan verb with `nu' ending": "Godan (ぬ)",
    "Godan verb with `ru' ending": "Godan (る)",
    "Godan verb with `ru' ending (irregular verb)": "Godan (る) (Irreg.)",
    "Godan verb with `su' ending": "Godan (す)",
    "Godan verb with `tsu' ending": "Godan (つ)",
    "Godan verb with `u' ending": "Godan (う)",
    "Godan verb with `u' ending (special class)": "Godan (う) (Special)",
    "Godan verb - Uru old class verb (old form of Eru)": "",
    "Ichidan verb - zuru verb (alternative form of -jiru verbs)": "",
    "intransitive verb": "Intrans. Verb",
    "Kuru verb - special class": "Verb (くる)",
    "irregular nu verb": "",
    "irregular ru verb, plain form ends with -ri": "",
    "noun or participle which takes the aux. verb suru": "",
    "su verb - precursor to the modern suru": "",
    "suru verb - special class": "する Verb (Special Class)",
    "suru verb - included": "する Verb (Included)",
    "Kyoto-ben": "Kyoto Region",
    "Osaka-ben": "Osaka Region",
    "Kansai-ben": "Kansai Region",
    "Kantou-ben": "Kantō Region",
    "Tosa-ben": "Tosa Region",
    "Touhoku-ben": "Tohoku Region",
    "Tsugaru-ben": "Tsugaru Region",
    "Kyuushuu-ben": "Kyūshū Region",
    "Ryuukyuu-ben": "Ryūkyū Region",
    "Nagano-ben": "Nagano Region",
    "Hokkaido-ben": "Hokkaido Region",
    "transitive verb": "Trans. Verb",
    "vulgar expression or word": "Vulgar",
    "`kari' adjective (archaic)": "",
    "`ku' adjective (archaic)": "",
    "`shiku' adjective (archaic)": "",
    "archaic/formal form of na-adjective": "",
    "proper noun": "Prop. Noun",
    "verb unspecified": "",
    "Yodan verb with `ku' ending (archaic)": "",
    "Yodan verb with `gu' ending (archaic)": "",
    "Yodan verb with `su' ending (archaic)": "",
    "Yodan verb with `tsu' ending (archaic)": "",
    "Yodan verb with `nu' ending (archaic)": "",
    "Yodan verb with `bu' ending (archaic)": "",
    "Yodan verb with `mu' ending (archaic)": "",
    "Nidan verb (upper class) with `ku' ending (archaic)": "",
    "Nidan verb (upper class) with `gu' ending (archaic)": "",
    "Nidan verb (upper class) with `tsu' ending (archaic)": "",
    "Nidan verb (upper class) with `dzu' ending (archaic)": "",
    "Nidan verb (upper class) with `hu/fu' ending (archaic)": "",
    "Nidan verb (upper class) with `bu' ending (archaic)": "",
    "Nidan verb (upper class) with `mu' ending (archaic)": "",
    "Nidan verb (upper class) with `yu' ending (archaic)": "",
    "Nidan verb (upper class) with `ru' ending (archaic)": "",
    "Nidan verb (lower class) with `ku' ending (archaic)": "",
    "Nidan verb (lower class) with `gu' ending (archaic)": "",
    "Nidan verb (lower class) with `su' ending (archaic)": "",
    "Nidan verb (lower class) with `zu' ending (archaic)": "",
    "Nidan verb (lower class) with `tsu' ending (archaic)": "",
    "Nidan verb (lower class) with `dzu' ending (archaic)": "",
    "Nidan verb (lower class) with `nu' ending (archaic)": "",
    "Nidan verb (lower class) with `hu/fu' ending (archaic)": "",
    "Nidan verb (lower class) with `bu' ending (archaic)": "",
    "Nidan verb (lower class) with `mu' ending (archaic)": "",
    "Nidan verb (lower class) with `yu' ending (archaic)": "",
    "Nidan verb (lower class) with `ru' ending (archaic)": "",
    "Nidan verb (lower class) with `u' ending and `we' conjugation (archaic)": "",
    "architecture term": "Architecture",
    "astronomy, etc. term": "Astronomy",
    "baseball term": "Baseball",
    "biology term": "Biology",
    "botany term": "Botany",
    "business term": "Business",
    "economics term": "Economics",
    "engineering term": "Engineering",
    "finance term": "Finance",
    "geology, etc. term": "Geology",
    "law, etc. term": "Law",
    "mahjong term": "Mahjong",
    "medicine, etc. term": "Medical",
    "music term": "Music",
    "Shinto term": "Shinto",
    "shogi term": "Shogi",
    "sports term": "Sports",
    "sumo term": "Sumo",
    "zoology term": "Zoology",
    "jocular, humorous term": "Humerous",
    "anatomical term": "Anatomical"
}