class ClassificationSimplifier:
    _CLASSIFICATIONS = {
        "martial arts term": "Martial Arts",
        "rude or X-rated term (not displayed in educational software)": "Offensive",
        "abbreviation": "Abbreviation",
        "adjective (keiyoushi)": "Adjective",
        "adjective (keiyoushi) - yoi/ii class": "Adj (良い/いい)",
        "adjectival nouns or quasi-adjectives (keiyodoshi)": "Adj. Noun",
        "nouns which may take the genitive case particle `no'": "Can Be Genitive (の)",
        "pre-noun adjectival (rentaishi)": "Attributive Noun",
        "`taru' adjective": "〜たる",
        "noun or verb acting prenominally": "Prenominal",
        "adverb (fukushi)": "Adverb",
        "adverb taking the `to' particle": "〜と",
        "archaism": "Archaic",
        "ateji (phonetic) reading": "Ateji",
        "auxiliary": "Auxiliary",
        "auxiliary verb": "Aux. Verb",
        "auxiliary adjective": "Aux. Adjective",
        "Buddhist term": "Buddhism",
        "chemistry term": "Chemistry",
        "children's language": "Juvenile",
        "colloquialism": "Colloquial",
        "computer terminology": "Computer",
        "conjunction": "Conjunction",
        "copula": "Copula",
        "counter": "Counter",
        "derogatory": "Derogatory",
        "exclusively kanji": "Only Kanji",
        "exclusively kana": "Only Kana",
        "expressions (phrases, clauses, etc.)": "Expression",
        "familiar language": "Familiar",
        "female term or language": "Feminine",
        "food term": "Food",
        "geometry term": "Geometry",
        "gikun (meaning as reading) or jukujikun (special kanji reading)": "Gikun/Jukujikun",
        "honorific or respectful (sonkeigo) language": "Honorific",
        "humble (kenjougo) language": "Humble",
        "word containing irregular kanji usage": "Irregular Kanji",
        "idiomatic expression": "Idiomatic",
        "word containing irregular kana usage": "Irregular Kana",
        "interjection (kandoushi)": "Interjection",
        "irregular okurigana usage": "Irregular Okurigana",
        "irregular verb": "Irregular Verb",
        "linguistics terminology": "Linguistic",
        "manga slang": "Manga",
        "male term or language": "Masculine",
        "male slang": "Male Slang",
        "mathematics": "Mathematical",
        "military": "Military",
        "noun (common) (futsuumeishi)": "Noun",
        "adverbial noun (fukushitekimeishi)": "Adv. Noun",
        "noun, used as a suffix": "Noun (Suffix)",
        "noun, used as a prefix": "Noun (Prefix)",
        "noun (temporal) (jisoumeishi)": "Noun (Temporal)",
        "numeric": "Numeric",
        "word containing out-dated kanji": "Outdated Kanji",
        "obsolete term": "Obsolete",
        "obscure term": "Obscure",
        "out-dated or obsolete kana usage": "Outdated Kana",
        "old or irregular kana form": "Irregular Kana",
        "onomatopoeic or mimetic word": "Onomatopeic",
        "pronoun": "Pronoun",
        "poetical term": "Poetical",
        "polite (teineigo) language": "Polite",
        "prefix": "Prefix",
        "proverb": "Proverb",
        "particle": "Particle",
        "physics terminology": "Physics",
        "quotation": "Quotation",
        "rare": "Rare",
        "sensitive": "Sensitive",
        "slang": "Slang",
        "suffix": "Suffix",
        "word usually written using kanji alone": "Usually Kanji",
        "word usually written using kana alone": "Usually Kana",
        "unclassified": "Unclassified",
        "yojijukugo": "Four Character Idiom",
        "Ichidan verb": "Ichidan",
        "Ichidan verb - kureru special class": "Ichidan (〜くれる)",
        "Nidan verb with 'u' ending (archaic)": "Nidan (〜う) (Archaic)",
        "Yodan verb with `hu/fu' ending (archaic)": "Yodan (〜ふ)",
        "Yodan verb with `ru' ending (archaic)": "Yodan (〜る)",
        "Godan verb - -aru special class": "Godan (ある)",
        "Godan verb with `bu' ending": "Godan (〜ぶ)",
        "Godan verb with `gu' ending": "Godan (〜ぐ)",
        "Godan verb with `ku' ending": "Godan (〜く)",
        "Godan verb - Iku/Yuku special class": "Godan （〜いく/〜ゆく)",
        "Godan verb with `mu' ending": "Godan (〜む)",
        "Godan verb with `nu' ending": "Godan (〜ぬ)",
        "Godan verb with `ru' ending": "Godan (〜る)",
        "Godan verb with `ru' ending (irregular verb)": "Godan (〜る) (Irreg.)",
        "Godan verb with `su' ending": "Godan (〜す)",
        "Godan verb with `tsu' ending": "Godan (〜つ)",
        "Godan verb with `u' ending": "Godan (〜う)",
        "Godan verb with `u' ending (special class)": "Godan (〜う) (Special)",
        "Godan verb - Uru old class verb (old form of Eru)": "Godan (〜うる)",
        "Ichidan verb - zuru verb (alternative form of -jiru verbs)": "Ichidan (〜ずる)",
        "intransitive verb": "Intrans. Verb",
        "Kuru verb - special class": "Verb (〜くる)",
        "irregular nu verb": "(〜ぬ) (Irregular)",
        "irregular ru verb, plain form ends with -ri": "(〜る) (Irregular)",
        "noun or participle which takes the aux. verb suru": "〜する",
        "su verb - precursor to the modern suru": "〜す",
        "suru verb - special class": "する Verb (Special Class)",
        "suru verb - included": "する Verb (Included)",
        "Kyoto-ben": "Kyoto Region",
        "Osaka-ben": "Osaka Region",
        "Kansai-ben": "Kansai Region",
        "Kantou-ben": "Kantō Region",
        "Tosa-ben": "Tosa Region",
        "Touhoku-ben": "Tohoku Region",
        "Tsugaru-ben": "Tsugaru Region",
        "Kyuushuu-ben": "Kyūshū Region",
        "Ryuukyuu-ben": "Ryūkyū Region",
        "Nagano-ben": "Nagano Region",
        "Hokkaido-ben": "Hokkaido Region",
        "transitive verb": "Trans. Verb",
        "vulgar expression or word": "Vulgar",
        "`kari' adjective (archaic)": "〜かり",
        "`ku' adjective (archaic)": "〜く",
        "`shiku' adjective (archaic)": "〜しく",
        "archaic/formal form of na-adjective": "Archaic/Formal 〜な",
        "proper noun": "Prop. Noun",
        "verb unspecified": "Verb Unspecified",
        "Yodan verb with `ku' ending (archaic)": "Yodan (〜く)",
        "Yodan verb with `gu' ending (archaic)": "Yodan (〜ぐ)",
        "Yodan verb with `su' ending (archaic)": "Yodan (〜す)",
        "Yodan verb with `tsu' ending (archaic)": "Yodan (〜つ)",
        "Yodan verb with `nu' ending (archaic)": "Yodan (〜ぬ)",
        "Yodan verb with `bu' ending (archaic)": "Yodan (〜ぶ)",
        "Yodan verb with `mu' ending (archaic)": "Yodan (〜む)",
        "Nidan verb (upper class) with `ku' ending (archaic)": "Nidan (Upper) (〜く)",
        "Nidan verb (upper class) with `gu' ending (archaic)": "Nidan (Upper) (〜ぐ)",
        "Nidan verb (upper class) with `tsu' ending (archaic)": "Nidan (Upper) (〜つ)",
        "Nidan verb (upper class) with `dzu' ending (archaic)": "Nidan (Upper) (〜づ)",
        "Nidan verb (upper class) with `hu/fu' ending (archaic)": "Nidan (Upper) (〜ふ)",
        "Nidan verb (upper class) with `bu' ending (archaic)": "Nidan (Upper) (〜ぶ)",
        "Nidan verb (upper class) with `mu' ending (archaic)": "Nidan (Upper) (〜む)",
        "Nidan verb (upper class) with `yu' ending (archaic)": "Nidan (Upper) (〜ゆ)",
        "Nidan verb (upper class) with `ru' ending (archaic)": "Nidan (Upper) (〜る)",
        "Nidan verb (lower class) with `ku' ending (archaic)": "Nidan (Lower) (〜く)",
        "Nidan verb (lower class) with `gu' ending (archaic)": "Nidan (Lower) (〜ぐ)",
        "Nidan verb (lower class) with `su' ending (archaic)": "Nidan (Lower) (〜す)",
        "Nidan verb (lower class) with `zu' ending (archaic)": "Nidan (Lower) (〜ず)",
        "Nidan verb (lower class) with `tsu' ending (archaic)": "Nidan (Lower) (〜つ)",
        "Nidan verb (lower class) with `dzu' ending (archaic)": "Nidan (Lower) (〜づ)",
        "Nidan verb (lower class) with `nu' ending (archaic)": "Nidan (Lower) (〜ぬ)",
        "Nidan verb (lower class) with `hu/fu' ending (archaic)": "Nidan (Lower) (〜ふ)",
        "Nidan verb (lower class) with `bu' ending (archaic)": "Nidan (Lower) (〜ぶ)",
        "Nidan verb (lower class) with `mu' ending (archaic)": "Nidan (Lower) (〜む)",
        "Nidan verb (lower class) with `yu' ending (archaic)": "Nidan (Lower) (〜ゆ)",
        "Nidan verb (lower class) with `ru' ending (archaic)": "Nidan (Lower) (〜る)",
        "Nidan verb (lower class) with `u' ending and `we' conjugation (archaic)": "Nidan (Lower) (う〜)　(ゑ)",
        "architecture term": "Architecture",
        "astronomy, etc. term": "Astronomy",
        "baseball term": "Baseball",
        "biology term": "Biology",
        "botany term": "Botany",
        "business term": "Business",
        "economics term": "Economics",
        "engineering term": "Engineering",
        "finance term": "Finance",
        "geology, etc. term": "Geology",
        "law, etc. term": "Law",
        "mahjong term": "Mahjong",
        "medicine, etc. term": "Medical",
        "music term": "Music",
        "Shinto term": "Shinto",
        "shogi term": "Shogi",
        "sports term": "Sports",
        "sumo term": "Sumo",
        "zoology term": "Zoology",
        "jocular, humorous term": "Humerous",
        "anatomical term": "Anatomical"
    }

    @staticmethod
    def simplify_term(term: str) -> str:
        if term in ClassificationSimplifier._CLASSIFICATIONS:
            return ClassificationSimplifier._CLASSIFICATIONS[term]
        return term